#ifndef RECURSIVELENGTHPREFIX_GLOBAL_H
#define RECURSIVELENGTHPREFIX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RECURSIVELENGTHPREFIX_LIBRARY)
#  define RECURSIVELENGTHPREFIX_EXPORT Q_DECL_EXPORT
#else
#  define RECURSIVELENGTHPREFIX_EXPORT Q_DECL_IMPORT
#endif

#endif // RECURSIVELENGTHPREFIX_GLOBAL_H
